Enable amalgamated compilation of multiple .pb.cc files
When second `.pb.cc` file is included, it results in a compiler error with msvc due to second use of init segment pragma:

> protobuf\AccountDataRequest.pb.cc(23,1): error C2356: initialization segment must not change during translation unit

This change makes it possible to avoid the error by defining `PROTOBUF_PRAGMA_INIT_SEG_USED` before second.pb.cc file is included